version: '3.8'

services:
  docs-processing:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - MAX_FILE_SIZE_MB=50
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Mount volume for development (uncomment for development)
    # volumes:
    #   - ./app:/app/app
    #   - ./cli.py:/app/cli.py 