version: '3.8'

services:
  app:
    build: .
    ports:
      - "8005:8005"
    env_file:
      - .env
    environment:
      # Enable EPUB processing by default
      - ENABLE_EPUB_PROCESSING=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 